apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-dev1
  namespace: demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-dev2
  namespace: demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-dev3
  namespace: demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-dev4
  namespace: demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-dev1-binding
  namespace: demo
subjects:
  - kind: ServiceAccount
    name: user-dev1
    namespace: demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-dev2-binding
  namespace: demo
subjects:
  - kind: ServiceAccount
    name: user-dev2
    namespace: demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-dev3-binding
  namespace: demo
subjects:
  - kind: ServiceAccount
    name: user-dev3
    namespace: demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-dev4-binding
  namespace: demo
subjects:
  - kind: ServiceAccount
    name: user-dev4
    namespace: demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
