{
 "title": "Loki - Logs Quickstart",
 "tags": [
  "loki",
  "logs",
  "quickstart"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values({job=~\".+\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values({namespace=~\"$namespace\"}, pod)"
   },
   { "name": "search", "label": "Contient (texte)", "query": "error" },
   {
    "name": "priority",
    "label": "Priorite Falco",
    "query": "label_values({namespace=\"falco\"}, priority)"
   }
  ]
 },
 "panels": [
  {
   "title": "Logs sur 5m",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"$namespace\", pod=~\"$pod\"} |= \"$search\" [5m]))"
    }
   ]
  },
  {
   "title": "Volume de logs (1m)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"$namespace\", pod=~\"$pod\"} [1m]))"
    }
   ]
  },
  {
   "title": "Falco - volume d evenements (1m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (priority) (count_over_time({namespace=\"falco\", priority=~\"$priority\"} [1m]))"
    }
   ]
  },
  {
   "title": "Falco - top regles",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "topk(5, sum by (rule) (count_over_time({namespace=\"falco\", priority=~\"$priority\"} [5m])))"
    }
   ]
  },
  {
   "title": "Logs filtres",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", pod=~\"$pod\"} |= \"$search\""
    }
   ]
  },
  {
   "title": "Falco - flux brut",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{namespace=\"falco\", priority=~\"$priority\"}"
    }
   ]
  }
 ]
}