
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno
    targetRevision: "3.8.1"
    helm:
      values: |
        admissionController:
          container:
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
          serviceMonitor:
            enabled: true
            interval: 30s
        backgroundController:
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
          serviceMonitor:
            enabled: true
            interval: 30s
        cleanupController:
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
          serviceMonitor:
            enabled: true
            interval: 30s
        reportsController:
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
          serviceMonitor:
            enabled: true
            interval: 30s
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
