
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno
    targetRevision: "3.8.1"
    helm:
      values: |
        admissionController:
          container:
            image:
              registry: ghcr.io
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
          initContainer:
            image:
              registry: ghcr.io
          serviceMonitor:
            enabled: true
            interval: 30s
        backgroundController:
          image:
            registry: ghcr.io
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          serviceMonitor:
            enabled: true
            interval: 30s
        cleanupController:
          image:
            registry: ghcr.io
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          serviceMonitor:
            enabled: true
            interval: 30s
        reportsController:
          image:
            registry: ghcr.io
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          serviceMonitor:
            enabled: true
            interval: 30s
        crds:
          migration:
            image:
              registry: ghcr.io
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
