apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "87.10.1"
    helm:
      values: |
        alertmanager:
          alertmanagerSpec:
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
        prometheusOperator:
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
        prometheus:
          prometheusSpec:
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
            serviceMonitorSelectorNilUsesHelmValues: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
