apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vulnerable-web
  namespace: demo
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: vulnerable-web.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vulnerable-web
                port:
                  number: 80
