apiVersion: v1
kind: Service
metadata:
  name: vulnerable-web
  namespace: demo
spec:
  type: ClusterIP
  selector:
    app: vulnerable-web
  ports:
    - name: http
      port: 80
      targetPort: 3000
