apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-limits
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-cpu-memory-limits
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - argocd
                - kyverno
                - monitoring
                - falco
                - trivy-system
                - remediator
      validate:
        message: Chaque conteneur doit declarer des limits CPU et memoire.
        pattern:
          spec:
            containers:
              - resources:
                  limits:
                    cpu: ?*
                    memory: ?*
